### ISSUE TITLE
File are missing

### ISSUE THREAD

**Issue by AmirRezaei** [Brackeys/NavMesh-Tutorial#5]
Files in Assets\Example05 - LowMan\LowMan\Models are missing. In the Video you assign a Avatar from Models folder. There no such file.

**Comment by abhiejam** [comment]
> Files in Assets\Example05 - LowMan\LowMan\Models are missing. In the Video you assign a Avatar from Models folder. There no such file.

Hi Amir,

For LowBody avatar to be visible, you have to click on the small play button on the low body model as shown in screenshot below:

<img width="431" alt="Capture 1" src="https://user-images.githubusercontent.com/40919913/73499001-00666780-4413-11ea-8d22-7099c000cdd0.PNG"><br>
<img width="430" alt="Capture 2" src="https://user-images.githubusercontent.com/40919913/73499007-03f9ee80-4413-11ea-8cbc-d3905b328019.PNG">

**Comment by AmirRezaei** [comment]
Great! Thanks!
